services:
  api:
    environment:
      API_DEBUG: "True"
      API_RELOAD: "True"
    volumes:
      - type: bind
        source: ./api/app
        target: /app/app
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./api/tools
        target: /app/tools
        read_only: true
        bind:
          create_host_path: false
